[mypy]
plugins = sqlalchemy.ext.mypy.plugin
python_version = 3.13
strict = True
ignore_missing_imports = True
explicit_package_bases = True
mypy_path = .
files = src
[mypy-src.tests.*]
disallow_untyped_decorators = false